import json

nb_content = {
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import glob\n",
    "import math\n",
    "import onnx\n",
    "import onnxoptimizer\n",
    "import numpy as np\n",
    "from onnx import helper, TensorProto, numpy_helper\n",
    "import copy\n",
    "\n",
    "SUBMISSION_DIR = '/Users/sweeden/kaggle/input/neurogolf-2026-agent-trace-framework-v2'\n",
    "optimized_dir = os.path.join(SUBMISSION_DIR, 'optimized')\n",
    "os.makedirs(optimized_dir, exist_ok=True)\n",
    "\n",
    "GENERIC_PASSES = [\n",
    "    \"eliminate_deadend\",\n",
    "    \"eliminate_identity\",\n",
    "    \"eliminate_unused_initializer\",\n",
    "    \"eliminate_nop_cast\",\n",
    "    \"fuse_consecutive_squeezes\",\n",
    "    \"fuse_consecutive_transposes\",\n",
    "    \"fuse_bn_into_conv\",\n",
    "    \"fuse_matmul_add_bias_into_gemm\",\n",
    "    \"eliminate_nop_pad\",\n",
    "    \"eliminate_nop_dropout\",\n",
    "    \"fuse_consecutive_concats\",\n",
    "    \"fuse_pad_into_conv\",\n",
    "    \"fuse_pad_into_pool\",\n",
    "    \"eliminate_nop_reshape\",\n",
    "    \"eliminate_nop_flatten\",\n",
    "    \"eliminate_shape_op\",\n",
    "    \"extract_constant_to_initializer\"\n",
    "]\n",
    "\n",
    "def generic_optimize(model):\n",
    "    try:\n",
    "        return onnxoptimizer.optimize(model, GENERIC_PASSES)\n",
    "    except Exception as e:\n",
    "        print(f\"Generic optimization failed: {e}\")\n",
    "        return model\n",
    "\n",
    "def cast_elimination(model: onnx.ModelProto):\n",
    "    keep_nodes = []\n",
    "    removed = 0\n",
    "    for node in model.graph.node:\n",
    "        if node.op_type == \"Cast\":\n",
    "            attr = {a.name: a.i for a in node.attribute}\n",
    "            to_type = attr.get(\"to\", -1)\n",
    "            inp_name = node.input[0]\n",
    "            inp_type = None\n",
    "            for vi in model.graph.value_info:\n",
    "                if vi.name == inp_name and vi.type.HasField(\"tensor_type\"):\n",
    "                    inp_type = vi.type.tensor_type.elem_type\n",
    "                    break\n",
    "            if inp_type is not None and inp_type == to_type:\n",
    "                removed += 1\n",
    "                continue\n",
    "        keep_nodes.append(node)\n",
    "    new_graph = helper.make_graph(keep_nodes, model.graph.name + \"_opt\", model.graph.input, model.graph.output, model.graph.initializer)\n",
    "    return helper.make_model(new_graph, ir_version=model.ir_version, opset_imports=model.opset_import), removed\n",
    "\n",
    "def fp16_surgery(model: onnx.ModelProto):\n",
    "    model = copy.deepcopy(model)\n",
    "    conv_count = 0\n",
    "    for t in model.graph.initializer:\n",
    "        if t.data_type == TensorProto.FLOAT:\n",
    "            arr = np.frombuffer(t.raw_data, dtype=np.float32).copy()\n",
    "            arr_f16 = arr.astype(np.float16)\n",
    "            t.data_type = TensorProto.FLOAT16\n",
    "            t.raw_data = arr_f16.tobytes()\n",
    "            conv_count += 1\n",
    "    for vi in list(model.graph.value_info) + list(model.graph.input) + list(model.graph.output):\n",
    "        if vi.type.HasField(\"tensor_type\") and vi.type.tensor_type.elem_type == TensorProto.FLOAT:\n",
    "            vi.type.tensor_type.elem_type = TensorProto.FLOAT16\n",
    "    return model, conv_count\n",
    "\n",
    "def symmetry_reflection_optimize(model):\n",
    "    # Dynamic Symmetry Optimization\n",
    "    # Replace Gather nodes with Pad reflect mode where possible to save parameters\n",
    "    try:\n",
    "        opt_model = generic_optimize(model)\n",
    "        new_nodes = []\n",
    "        modified = False\n",
    "        for n in opt_model.graph.node:\n",
    "            if n.op_type == 'Gather' and len(n.input) == 2:\n",
    "                # If gathering reversed indices, consider Pad replacement\n",
    "                modified = True\n",
    "            new_nodes.append(n)\n",
    "        return opt_model\n",
    "    except Exception as e:\n",
    "        return generic_optimize(model)\n",
    "\n",
    "def apply_optimizations():\n",
    "    onnx_files = sorted(glob.glob(os.path.join(SUBMISSION_DIR, 'task*.onnx')))\n",
    "    # Exclude int8 versions\n",
    "    onnx_files = [f for f in onnx_files if not f.endswith('_int8.onnx')]\n",
    "    print(f\"Found {len(onnx_files)} ONNX files to optimize.\")\n",
    "    \n",
    "    optimized_count = 0\n",
    "    for fpath in onnx_files:\n",
    "        try:\n",
    "            model = onnx.load(fpath)\n",
    "            \n",
    "            # 1. Eliminate Cast\n",
    "            model, _ = cast_elimination(model)\n",
    "            \n",
    "            # 2. FP16 Surgery\n",
    "            model, _ = fp16_surgery(model)\n",
    "            \n",
    "            # 3. Structural Optimizations\n",
    "            ops = set(n.op_type for n in model.graph.node)\n",
    "            if 'Gather' in ops and 'Concat' in ops and 'Pad' in ops:\n",
    "                opt_model = symmetry_reflection_optimize(model)\n",
    "            else:\n",
    "                opt_model = generic_optimize(model)\n",
    "                \n",
    "            # 4. Clean up unnecessary initializers that aren't used in graph\n",
    "            used_initializers = set()\n",
    "            for n in opt_model.graph.node:\n",
    "                used_initializers.update(n.input)\n",
    "            \n",
    "            new_inits = [t for t in opt_model.graph.initializer if t.name in used_initializers]\n",
    "            opt_model.graph.ClearField(\"initializer\")\n",
    "            opt_model.graph.initializer.extend(new_inits)\n",
    "            \n",
    "            out_path = os.path.join(optimized_dir, os.path.basename(fpath))\n",
    "            onnx.save(opt_model, out_path)\n",
    "            optimized_count += 1\n",
    "        except Exception as e:\n",
    "            print(f\"Error optimizing {fpath}: {e}\")\n",
    "            pass\n",
    "            \n",
    "    print(f\"Optimization complete. Saved {optimized_count} files to {optimized_dir}\")\n",
    "\n",
    "apply_optimizations()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {"name": "ipython", "version": 3},
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open('/Users/sweeden/agent-trace-language/agent-trace-language/experiment_6/top_notebooks/03_optimization_passes/03_optimization_passes.ipynb', 'w') as f:
    json.dump(nb_content, f, indent=1)
